#define STANDARD_SM_SUPPORTED
#define RVMODEL_PMP_GRAIN 1
#define RVMODEL_NUM_PMPS 16
#define ZAAMO_SUPPORTED
#define ZCA_SUPPORTED
#define ZCB_SUPPORTED
#define ZBA_SUPPORTED
#define ZBB_SUPPORTED
#define ZBKB_SUPPORTED
#define ZBKC_SUPPORTED
#define ZBKX_SUPPORTED
#define ZBK_SUPPORTED
#define ZBS_SUPPORTED
#define ZICNTR_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZIMOP_SUPPORTED
#define ZKND_SUPPORTED
#define ZKNE_SUPPORTED
#define ZKNH_SUPPORTED
#define ZKSED_SUPPORTED
#define ZKSH_SUPPORTED
#define SMCNTRPMF_SUPPORTED
