#define CONFORMING_SM_SUPPORTED
#define RVMODEL_PMP_GRAIN 1
#define RVMODEL_NUM_PMPS 16
#define ZICNTR_SUPPORTED
#define ZBB_SUPPORTED
#define ZBA_SUPPORTED
#define ZBS_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCB_SUPPORTED
